name = input("Введите имя: ")
(age) = input("Введите возвраст: ")
age = int(age)
city = input("В каком городе живете? ")
hobby = input("Каково ваше увлечение? ")
print("====================")
print("  АНКЕТА УЧАСТНИКА  ")
print("====================")
print(f"Имя: {name}")
print(f"Возвраст: {age}")
print(f"Город: {city}")
print(f"Увлечение: {hobby}")
print(f"Через 5 лет мне будет:{age + 5}")
