name = input("Введите ваше имя: ")
product = input("Введите название товара: ")
price = input('Введите цену: ')
amount = input('Введите количество товара: ')
price = int(price)
amount = int(amount)
stoimost = (price * amount)
"""print(f"Имя: {name}")
print(f"Товар: {product}")
print(f'Цена: {price}')
print(f'Количество: {amount}')"""
print()
print("===== ВАШ ЧЕК =====")
print(f"Покупатель: {name}")
print(f'Товар: {product}')
print(f'Количество: {amount}')
a = (price * amount)
print(f"Итого: {a}")