print("Здравтвуйте!")
print("Как вас зовут?")
n = input()
print("Сколько вам лет?")
y = int(input())
print(f"Приятно познакомиться, {n}")
a = y + 5
print(f"Через 5 лет вам будет {a} лет")
print("Введите первое число для вычислений")
f = int((input()))
print("Введите второе число для вычислений")
s = int((input()))
print("Сумма чисел:")
f = int(f)
s = int(s)
print(f+s)
print("Разность чисел:")
print(f-s)
print("Произведение чисел:")
print(f*s)
print("Результат деления:")
print(f/s)
